feat(pageviews): enable filters for checkpoint, source, and target
adobe/helix-run-query pull request #1054
Opened 2024-02-14 21:09 UTC by trieloff

2024-02-14 23:57 UTC, langswei commented
From reading, not yet testing -- the UNION ALL technique as a replacement for CASE is quite clever.  This is easier to read than the previous version, perhaps not quite as efficient given the multiple EVENTS_V3 table function calls but likely still very fast.

I'm not confident that the TIMESTAMP_TRUNC with a default or non-negative offset+interval will give us what we want but will reserve judgment until after testing.  For example, I imagine a mid-February call of `granularity=30&interval=3` with default `offset=0` would return half of November, all of December, all of January, and half of February.  Maybe there is no more sensible behavior and the user will just learn to work with it.

An automated test fails.  If you don't get to this during your day, I can check it out during my day.

2024-02-15 05:49 UTC, MarquiseRosier requested changes

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 7, # offset in weeks
This needs to be cast to int64 as Events_V3  expects in64, int64 for those two in the signature.

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 7, # weeks to fetch
this also needs to be cast to int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 30, # offset in months
int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 30, # months to fetch
int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 90, # offset in quarters
cast to int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 90, # quarters to fetch
cast to int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 365, # offset in years
cast as int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 365, # years to fetch
cast as int64

2024-02-15 05:49 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset, # offset
```suggestion
    CAST(@offset as INT64), # offset
```

2024-02-15 05:52 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval, # days to fetch
```suggestion
    CAST(@interval as INT64), # days to fetch
```

2024-02-15 05:57 UTC, MarquiseRosier requested changes
I think these need to be casted to INT64 before the multiplication! :)

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 7, # offset in weeks
```suggestion
    CAST(@offset AS INT64) * 7, # offset in weeks
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 7, # weeks to fetch
```suggestion
    CAST(@interval AS INT64) * 7, # weeks to fetch
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 30, # offset in months
```suggestion
    CAST(@offset AS INT64) * 30, # offset in months
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 30, # months to fetch
```suggestion
    CAST(@interval AS INT64) * 30, # months to fetch
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 90, # offset in quarters
```suggestion
    CAST(@offset AS INT64) * 90, # offset in quarters
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 90, # quarters to fetch
```suggestion
    CAST(@interval AS INT64) * 90, # quarters to fetch
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @offset * 365, # offset in years
```suggestion
    CAST(@offset AS INT64) * 365, # offset in years
```

2024-02-15 05:57 UTC, MarquiseRosier commented on src/queries/rum-pageviews.sql
> +    @interval * 365, # years to fetch
```suggestion
    CAST(@interval AS INT64) * 365, # years to fetch
```

2024-02-15 14:23 UTC, trieloff commented
> perhaps not quite as efficient given the multiple EVENTS_V3 table function calls but likely still very fast.
The query optimizer seems to be clever enough not to expand the CTE before evaluating the `WHERE` statement, so we are not overfetching

2024-02-15 19:48 UTC, MarquiseRosier approved these changes

2024-02-16 10:39 UTC, merged

2024-02-16 10:42 UTC, trieloff commented
:tada: This PR is included in version 3.13.0 :tada:

The release is available on:
- `v3.13.0`
- [GitHub release](https://github.com/adobe/helix-run-query/releases/tag/v3.13.0)
- `v3.13.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: